#!/usr/bin/env bash

jazzy \
  --clean \
  --author "Dan Trenz" \
  --github_url https://github.com/dtrenz/SettingsKit \
  --module-version 0.1.0 \
  --xcodebuild-arguments -scheme,SettingsKit \
  --module SettingsKit \
  --output docs
